# Generated by Django 6.0.1 on 2026-03-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_orderitem_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='variations',
            field=models.ManyToManyField(blank=True, related_name='store_variations', to='store.variation'),
        ),
    ]
