# Generated by Django 6.0.1 on 2026-03-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/reviews/'),
        ),
    ]
