# Generated by Django 6.0.1 on 2026-03-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_reviewrating_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
    ]
