# Generated by Django 6.0.1 on 2026-03-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
