
[phases.build]
cmds = [
    "mkdir -p staticfiles",
    "python manage.py collectstatic --no-input"
]

[start]
cmd = "python manage.py migrate --fake-initial --no-input && gunicorn E_Commerce.wsgi:application --bind 0.0.0.0:$PORT"

[setup]
providers = ["python"]
