# Generated by Django 6.0.2 on 2026-02-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_is_superadmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('distributor', 'Distributor')], default='customer', max_length=20),
        ),
    ]
