# Generated by Django 6.0.1 on 2026-03-30 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_order_items', to='store.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variations',
            field=models.ManyToManyField(blank=True, related_name='orders_variations', to='store.variation'),
        ),
        migrations.AddField(
            model_name='printorder',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.address'),
        ),
        migrations.AddField(
            model_name='printorder',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.distributor'),
        ),
        migrations.AddField(
            model_name='printorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_order_items', to='store.product'),
        ),
        migrations.AddField(
            model_name='printorder',
            name='store_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_orders', to='store.orderitem'),
        ),
        migrations.AddField(
            model_name='printorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='printorder',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
        migrations.AddField(
            model_name='return',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='store.order'),
        ),
        migrations.AddField(
            model_name='return',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadeddesign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='printorder',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.uploadeddesign'),
        ),
    ]
