# Generated by Django 6.0.1 on 2026-03-11 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_product_alter_printorder_product_and_more'),
        ('store', '0008_alter_orderitem_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variations',
            field=models.ManyToManyField(blank=True, related_name='orders_variations', to='store.variation'),
        ),
        migrations.AddField(
            model_name='printorder',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_order_items', to='store.product'),
        ),
    ]
