# Generated by Django 6.0.1 on 2026-03-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_variations_printorder_variations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
