# Generated by Django 6.0.1 on 2026-03-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_printorder_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printorder',
            name='cvv',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='printorder',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
