# Generated by Django 6.0.1 on 2026-03-17 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_printorder_card_number_printorder_cvv_and_more'),
        ('store', '0012_orderitem_status_orderitem_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='store_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_orders', to='store.orderitem'),
        ),
    ]
