# Generated by Django 6.0.1 on 2026-03-18 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_return'),
        ('store', '0012_orderitem_status_orderitem_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='store.order'),
        ),
    ]
